[tool.poetry]
name = "jax-tg"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.12"
jax = {extras = ["cpu"], version = "0.4.31"}
equinox = "0.11.5"
optax = "0.2.3"


[tool.poetry.group.dev.dependencies]
jupyterlab = "4.2.5"
ruff = "0.6.2"
pandas = "2.2.2"
matplotlib = "3.9.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
