[tool.poetry]
name = "jax-tg"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"
jax = {extras = ["cpu"], version = "^0.4.30"}
equinox = "^0.11.4"
optax = "^0.2.3"


[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.2.4"
ruff = "^0.4.10"
pandas = "^2.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
