[tool.poetry]
name = "jax-tg"
version = "0.1.0"
description = ""
authors = ["Thomas Zub <thomas.zub@outlook.de>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "3.12.4"
jax = {extras = ["cpu"], version = "0.4.30"}
equinox = "0.11.4"
optax = "0.2.3"


[tool.poetry.group.dev.dependencies]
jupyterlab = "4.2.4"
ruff = "0.5.5"
pandas = "2.2.2"
matplotlib = "3.9.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
